### ISSUE TITLE
This is so cool

### ISSUE THREAD

**Issue by om3ga6400** [GD-JumpStart/Application#2]
Hi! I have found a few issues; the discord login doesn't work, on the site the premium tab url doesn't exist, also on the site and the app the discord login doesn't work and lastly, the store in the app doesn't load. This is a really cool project and i hope it gets even better!

**Comment by KontrollFreek** [comment]
Hi there, sorry for the long response time.
This has been a known issue for several months but unfortunately i never had time to properly fix it
The API server is offline currently but should be active again very soon. Please keep up to date with the Releases tab for an update to fix this releasing in around the next 24 hours. Thanks!

**Comment by om3ga6400** [comment]
yay

**Comment by OM3GA6400** [comment]
@KontrollFreek if i Sponsored this project, how much would make you happy?

**Comment by KontrollFreek** [comment]
Considering I do this all for free anyways I'd be extremely thankful for any sort of donation
